### ISSUE TITLE
`inherit` should be accepted for `color`

### ISSUE THREAD

**Issue by silverwind** [csstree/stylelint-validator#27]
According to [the spec](https://drafts.csswg.org/css-color-3/#annotation_foreground), `inherit` is a valid value for the `color` property but it's being rejected:

````css
a { color: inherit } /* Invalid value for `color` */
````

I assume this is an issue for many if not all properties that can take `<color>`.
