### ISSUE TITLE
Ignoring value containing colon

### ISSUE THREAD

**Issue by AndreasNasman** [csstree/stylelint-validator#43]
Hi!

I'm trying to use [`ignoreValue`](https://github.com/csstree/stylelint-validator#ignorevalue) to suppress a parsing error:

```shell
Can't parse value "alpha( opacity: 0 )"
```

The CSS property looks like this:

```css
.class {
    filter: alpha( opacity: 0 );
}
```

I've tried combinations like

```js
'ignoreValue': 'alpha'
'ignoreValue': 'alpha.*'
'ignoreValue': 'alpha\\(.*\\)'
```

to ignore the value, but can't seem to get the syntax right. Any advice on the correct syntax to ignore the `filter: alpha( opacity: 0 );` property?

Thanks
– Andreas

**Comment by AndreasNasman** [comment]
Another similar one is

```css
.class {
    filter: progid:dximagetransform.microsoft.gradient( startColorstr='#e80008', endColorstr='#a6002c', GradientType=0 ); 
}
```

It seems to be the colons in the properties that cause trouble. 🤔
