### ISSUE TITLE
Support for the CSS Color Module Level 4 (Editor's Draft)

### ISSUE THREAD

**Issue by jeddy3** [csstree/stylelint-validator#8]
It's very exciting to watch so many of the [`1.0` roadmap items](https://github.com/csstree/csstree/issues/29) get ticked-off! 

I was wondering if support for the [CSS Color Module Level 4 (Editor's Draft)](https://drafts.csswg.org/css-color/) was under consideration, in particular, the [`color()`](https://drafts.csswg.org/css-color/#modifying-colors) function (playground [here](https://colorme.io/))?

Currently the following CSS:

```css
a { 
  color: color(#eef6f8 alpha(50%));
  border-bottom: 2px solid color(#eef6f8 alpha(30%));
}
```

Produces the following warnings:

```console
2:2  ✖  Invalid value for `color`   csstree/validator
3:2  ✖  The rest part of value can't to be matched on `border-bottom` syntax   csstree/validator
```
